# Generated by Django 4.0.6 on 2022-08-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehicleModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('engine_capacity', models.IntegerField()),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('colour', models.CharField(max_length=20)),
                ('slug', models.SlugField(null=True)),
            ],
        ),
    ]
