# Generated by Django 4.0.6 on 2022-08-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelApp', '0002_alter_vehiclemodels_engine_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemodels',
            name='colour',
            field=models.CharField(choices=[('blue', 'Blue'), ('red', 'Red'), ('black', 'Black')], default='Black', max_length=20),
        ),
    ]
