# Generated by Django 4.0.6 on 2022-08-02 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclemodels',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vehiclemodels',
            name='image',
        ),
    ]
