# Generated by Django 4.0.6 on 2022-08-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewApp', '0002_remove_vehiclemodels_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemodels',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
